// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubohogjzelswipuhlsjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVib2hvZ2p6ZWxzd2lwdWhsc2p0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNTkwMTEsImV4cCI6MjA2NTYzNTAxMX0.m2PjBpDsojG0HKjY22UQUhynw-60l71yyRXni2B2KsI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);